# Generated by Django 2.0.6 on 2022-04-18 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NTNotification', '0001_initial'),
        ('NTWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='CommentInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CObject', to='NTWebsite.CommentInfo', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='notice',
            name='RollCallDialogue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RDObject', to='NTWebsite.RollCallDialogue', verbose_name='点名对话'),
        ),
        migrations.AddField(
            model_name='notice',
            name='RollCallInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RObject', to='NTWebsite.RollCallInfo', verbose_name='点名'),
        ),
        migrations.AddField(
            model_name='notice',
            name='SourceUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NSourceUser', to=settings.AUTH_USER_MODEL, verbose_name='通知者'),
        ),
        migrations.AddField(
            model_name='notice',
            name='TargetUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NTargetUser', to=settings.AUTH_USER_MODEL, verbose_name='被通知者'),
        ),
        migrations.AddField(
            model_name='notice',
            name='TopicInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TAObject', to='NTWebsite.TopicInfo', verbose_name='书评'),
        ),
        migrations.AddField(
            model_name='notice',
            name='UserLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LObject', to='NTWebsite.UserLink', verbose_name='被关注者'),
        ),
    ]
