# Generated by Django 2.0.6 on 2022-04-19 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0002_topiccategoryinfo_ratingnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccategoryinfo',
            name='RatingNumber',
            field=models.IntegerField(default=0, verbose_name='评分人数'),
        ),
        migrations.AlterField(
            model_name='topicinfo',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topic', to='NTWebsite.TopicCategoryInfo', verbose_name='书评类别'),
        ),
        migrations.AlterField(
            model_name='topicinfo',
            name='Publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Topic', to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
