# Generated by Django 2.0.6 on 2022-04-19 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0003_auto_20220419_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicinfo',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topic_Category', to='NTWebsite.TopicCategoryInfo', verbose_name='书评类别'),
        ),
        migrations.AlterField(
            model_name='topicinfo',
            name='Publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Topic_User', to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='topicinfo',
            name='Theme',
            field=models.ManyToManyField(related_name='Topic_Theme', to='NTWebsite.TopicThemeInfo', verbose_name='书评标签'),
        ),
    ]
