# Generated by Django 2.0.6 on 2022-04-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTWebsite', '0004_auto_20220419_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicinfo',
            name='Rating',
            field=models.FloatField(default=0, verbose_name='评分'),
        ),
    ]
